//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OwlSpace.UserService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsersSoap", Namespace="http://tempuri.org/")]
    public partial class Users : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback adminViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteCourseOperationCompleted;
        
        private System.Threading.SendOrPostCallback catalogViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback detailsViewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Users() {
            this.Url = global::OwlSpace.Properties.Settings.Default.OwlSpace_UserService_Users;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event adminViewCompletedEventHandler adminViewCompleted;
        
        /// <remarks/>
        public event addCourseCompletedEventHandler addCourseCompleted;
        
        /// <remarks/>
        public event deleteCourseCompletedEventHandler deleteCourseCompleted;
        
        /// <remarks/>
        public event catalogViewCompletedEventHandler catalogViewCompleted;
        
        /// <remarks/>
        public event detailsViewCompletedEventHandler detailsViewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/adminView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet adminView() {
            object[] results = this.Invoke("adminView", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void adminViewAsync() {
            this.adminViewAsync(null);
        }
        
        /// <remarks/>
        public void adminViewAsync(object userState) {
            if ((this.adminViewOperationCompleted == null)) {
                this.adminViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadminViewOperationCompleted);
            }
            this.InvokeAsync("adminView", new object[0], this.adminViewOperationCompleted, userState);
        }
        
        private void OnadminViewOperationCompleted(object arg) {
            if ((this.adminViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adminViewCompleted(this, new adminViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addCourse(string title, string description, string hours, string program, string crn, string prereq, string repeat, string semester) {
            object[] results = this.Invoke("addCourse", new object[] {
                        title,
                        description,
                        hours,
                        program,
                        crn,
                        prereq,
                        repeat,
                        semester});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addCourseAsync(string title, string description, string hours, string program, string crn, string prereq, string repeat, string semester) {
            this.addCourseAsync(title, description, hours, program, crn, prereq, repeat, semester, null);
        }
        
        /// <remarks/>
        public void addCourseAsync(string title, string description, string hours, string program, string crn, string prereq, string repeat, string semester, object userState) {
            if ((this.addCourseOperationCompleted == null)) {
                this.addCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCourseOperationCompleted);
            }
            this.InvokeAsync("addCourse", new object[] {
                        title,
                        description,
                        hours,
                        program,
                        crn,
                        prereq,
                        repeat,
                        semester}, this.addCourseOperationCompleted, userState);
        }
        
        private void OnaddCourseOperationCompleted(object arg) {
            if ((this.addCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCourseCompleted(this, new addCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteCourse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteCourse(string title, string program, string crn) {
            object[] results = this.Invoke("deleteCourse", new object[] {
                        title,
                        program,
                        crn});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteCourseAsync(string title, string program, string crn) {
            this.deleteCourseAsync(title, program, crn, null);
        }
        
        /// <remarks/>
        public void deleteCourseAsync(string title, string program, string crn, object userState) {
            if ((this.deleteCourseOperationCompleted == null)) {
                this.deleteCourseOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteCourseOperationCompleted);
            }
            this.InvokeAsync("deleteCourse", new object[] {
                        title,
                        program,
                        crn}, this.deleteCourseOperationCompleted, userState);
        }
        
        private void OndeleteCourseOperationCompleted(object arg) {
            if ((this.deleteCourseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCourseCompleted(this, new deleteCourseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/catalogView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet catalogView() {
            object[] results = this.Invoke("catalogView", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void catalogViewAsync() {
            this.catalogViewAsync(null);
        }
        
        /// <remarks/>
        public void catalogViewAsync(object userState) {
            if ((this.catalogViewOperationCompleted == null)) {
                this.catalogViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OncatalogViewOperationCompleted);
            }
            this.InvokeAsync("catalogView", new object[0], this.catalogViewOperationCompleted, userState);
        }
        
        private void OncatalogViewOperationCompleted(object arg) {
            if ((this.catalogViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.catalogViewCompleted(this, new catalogViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/detailsView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet detailsView(string title, string program, string crn) {
            object[] results = this.Invoke("detailsView", new object[] {
                        title,
                        program,
                        crn});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void detailsViewAsync(string title, string program, string crn) {
            this.detailsViewAsync(title, program, crn, null);
        }
        
        /// <remarks/>
        public void detailsViewAsync(string title, string program, string crn, object userState) {
            if ((this.detailsViewOperationCompleted == null)) {
                this.detailsViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OndetailsViewOperationCompleted);
            }
            this.InvokeAsync("detailsView", new object[] {
                        title,
                        program,
                        crn}, this.detailsViewOperationCompleted, userState);
        }
        
        private void OndetailsViewOperationCompleted(object arg) {
            if ((this.detailsViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.detailsViewCompleted(this, new detailsViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void adminViewCompletedEventHandler(object sender, adminViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adminViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal adminViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void addCourseCompletedEventHandler(object sender, addCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void deleteCourseCompletedEventHandler(object sender, deleteCourseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCourseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCourseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void catalogViewCompletedEventHandler(object sender, catalogViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class catalogViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal catalogViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void detailsViewCompletedEventHandler(object sender, detailsViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class detailsViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal detailsViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591